# baseURL = "https://madsys.seas.harvard.edu/"
baseURL = "https://systems.seas.harvard.edu/"
title = "Harvard Systems Group"
author = "Harvard John A. Paulson School of Engineering and Applied Sciences"
copyright = "Copyright Â© 2026 The President and Fellows of Harvard College"
theme = "paper"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
googleAnalytics = 'G-8MX7PPSYRT'
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
[pagination]
  pagerSize = 10

# ------------------------------

[params]
  description = "This is the site of the Harvard Systems Group at Harvard John A. Paulson School of Engineering and Applied Sciences. We explore systems, networking, databases, and computer architecture that power modern computing."
  color = 'light'
  # twitter = 'HarvardSystems'
  github = 'HarvardSys'
  mainSections = ['blog']
  math = true

# avatar = 'nanxiaobei@gmail.com'
  # name = 'Lee'
  # bio = 'Discover fresh context'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "people"
    name = "People"
    url = "/people/"
    weight = 10
  [[menu.main]]
    identifier = "seminar"
    name = "Seminars"
    url = "/seminar/"
    weight = 30
  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 40
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 50

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.x]
    disableInlineCSS = true
